# Generated by Django 2.1.5 on 2026-03-15 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('body_part', models.CharField(max_length=25)),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('userid_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_initiated', to=settings.AUTH_USER_MODEL)),
                ('userid_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('set_num', models.SmallIntegerField()),
                ('reps', models.SmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('duration', models.SmallIntegerField()),
                ('failure', models.BooleanField()),
                ('exerciseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fittrack.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField()),
                ('sets', models.SmallIntegerField()),
                ('reps', models.SmallIntegerField()),
                ('exerciseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fittrack.Exercise')),
                ('workoutid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fittrack.Workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workoutid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fittrack.Workout')),
            ],
        ),
        migrations.AddField(
            model_name='setlog',
            name='sessionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fittrack.WorkoutSession'),
        ),
    ]
