# Generated by Django 2.1.5 on 2026-03-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fittrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
