# Generated by Django 2.1.5 on 2026-03-04 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fittrack', '0002_auto_20260304_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('body_part', models.CharField(max_length=25)),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fittrack.User')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fittrack.User')),
            ],
        ),
    ]
