# Generated by Django 2.1.5 on 2026-03-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fittrack', '0002_auto_20260315_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setlog',
            name='duration',
        ),
    ]
