# Generated by Django 2.1.5 on 2026-03-17 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fittrack', '0003_remove_setlog_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setlog',
            options={'ordering': ['set_num']},
        ),
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='userid_a',
            new_name='user_a',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='userid_b',
            new_name='user_b',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_answer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_question',
            field=models.CharField(choices=[('pet', 'What was the name of your first pet?'), ('school', 'What primary school did you attend?'), ('city', 'In what city were you born?'), ('food', 'What is your favourite food?'), ('friend', "What is your best friend's name?")], default='pet', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('user_a', 'user_b')},
        ),
    ]
