# Generated by Django 2.1.5 on 2026-03-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fittrack', '0003_exercise_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('userid_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_initiated', to='fittrack.User')),
                ('userid_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to='fittrack.User')),
            ],
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('set_num', models.SmallIntegerField()),
                ('reps', models.SmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('duration', models.SmallIntegerField()),
                ('failure', models.BooleanField()),
                ('exerciseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fittrack.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField()),
                ('sets', models.SmallIntegerField()),
                ('reps', models.SmallIntegerField()),
                ('exerciseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fittrack.Exercise')),
                ('workoutid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fittrack.Workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fittrack.User')),
                ('workoutid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fittrack.Workout')),
            ],
        ),
        migrations.AddField(
            model_name='setlog',
            name='sessionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fittrack.WorkoutSession'),
        ),
    ]
