# Generated by Django 2.1.5 on 2026-03-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fittrack', '0004_auto_20260317_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='ownerid',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='setlog',
            old_name='exerciseid',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='setlog',
            old_name='sessionid',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='ownerid',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='workoutexercise',
            old_name='exerciseid',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='workoutexercise',
            old_name='workoutid',
            new_name='workout',
        ),
        migrations.RenameField(
            model_name='workoutsession',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='workoutsession',
            old_name='workoutid',
            new_name='workout',
        ),
    ]
