# Generated by Django 2.1.5 on 2026-03-17 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fittrack', '0005_auto_20260317_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'M'), (1, 'T'), (2, 'W'), (3, 'T'), (4, 'F'), (5, 'S'), (6, 'S')])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_workouts', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fittrack.Workout')),
            ],
            options={
                'ordering': ['day', 'order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='plannedworkout',
            unique_together={('user', 'day', 'order')},
        ),
    ]
