# Generated by Django 2.1.5 on 2026-03-17 22:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fittrack', '0007_auto_20260317_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannedworkout',
            options={'ordering': ['day', 'order']},
        ),
        migrations.AddField(
            model_name='plannedworkout',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='plannedworkout',
            unique_together={('user', 'day', 'order')},
        ),
    ]
