# Generated by Django 2.1.5 on 2026-03-17 22:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fittrack', '0008_auto_20260317_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannedworkout',
            options={'ordering': ['day']},
        ),
        #migrations.RemoveField(
        #    model_name='plannedworkout',
        #    name='order',
        #),
        migrations.AlterUniqueTogether(
            name='plannedworkout',
            unique_together={('user', 'day')},
        ),
    ]
