# Generated by Django 2.1.5 on 2026-03-17 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fittrack', '0009_auto_20260317_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedworkout',
            name='order',
        ),
    ]
